name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps:
         - name: Log the node version
           run: |
            
             echo "-----------"
         - name: Update GitHub Profile README
           uses: theboi/github-update-readme@v1.0
           env:
             GITHUB_TOKEN: ${{ secrets.TOKEN_NF }}
           with:
             header: "Hey, I'm NF! 👋"
             subhead: "Currently a student in Singapore, passionate about creating all-things-tech to improve society."
             footer: "**Learn more about me at [ryanthe.com](https://www.NF.com)!**"  
          