name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16
      volumes: 
       - ${{ github.workspace }}:/workspace
    steps:
           env:
            NODE_OPTIONS: "--max-old-space-size=4096"
         - name: Log the node version
           run: |
             node -v
             echo "-----------"
             
         - name: Checkout repository
           uses: actions/checkout@v2
         - name: npm install
           run: npm install
         - name: npm build
           run: npm run build
          